### ISSUE TITLE
Factorize code

### ISSUE THREAD

**Issue by charlesfleche** [CarloCattano/PopularSynth#1]
Hey @CarloCattano ,

This is Charles, we've met yesterday at Spektrum and talked about Motion Capture for dancers. I went through the PopularSynth code and I think there are some room for improvement, especially in refactoring the code to make further development faster. I'd love to go ahead and submit patches, but one thing was unclear yesterday about the eventual goal of the project: do you expect each user to run it's own instance of the synth on his own device (own sound stream per user) or do you want each user to collaboratively edit the parameters of a single synth instance ?

Thanks,

**Comment by CarloCattano** [comment]
hey. thanks for passing by!
the idea is that each user gets redirected depending on their position on
the clients list. i need to fix some issues with it still, but in theory
every user get one of the current 5 different html that you can see in the
home.html
the code is very raw still and needs more documenting etc.
each user should have a sound generating patch with some degree of
interactivity.
the home.html system is quite new that's why can be confusing since it's
messing with the array of clients once they are redirected they get a new
socket id, i will see how i can fix that. I'm using the socket.id and
storing it in an array on the server. js to query it afterwards from client

**Comment by charlesfleche** [comment]
OK, I understood that each new client gets assigned a synth each time they connect. But you don't have plan to have several users tweaking the same sound stream at the same time, right ?

**Comment by CarloCattano** [comment]
each user tweaks their own generated audio only. since audio generation is
client side. if I get your question well, there is no comunication between
clients

**Comment by charlesfleche** [comment]
OK, perfect. Let me try something to clean the code and solve your IP assign issues. I'll send your a pull request.

**Comment by CarloCattano** [comment]
cool, thanks. I'm using require ip module now but still didn't implement it
on the clients. will let you know when I have the time to sit again for it
